// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxgO2lv2dvYlyVbqlgDqR1YAmh1bBq_t0',
    appId: '1:559471513334:web:640ee66a2011eb7ac6a6d7',
    messagingSenderId: '559471513334',
    projectId: 'sert-bec19',
    authDomain: 'sert-bec19.firebaseapp.com',
    storageBucket: 'sert-bec19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjzxV-z9lESdiL1Y8wUAZZvLX18J00qWw',
    appId: '1:559471513334:android:5f0f493c65a1c53fc6a6d7',
    messagingSenderId: '559471513334',
    projectId: 'sert-bec19',
    storageBucket: 'sert-bec19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0hMc3fUqjRvC8mz5sVUbeC_LyMZHRUz0',
    appId: '1:559471513334:ios:371796d88842bd60c6a6d7',
    messagingSenderId: '559471513334',
    projectId: 'sert-bec19',
    storageBucket: 'sert-bec19.appspot.com',
    iosBundleId: 'com.example.sert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0hMc3fUqjRvC8mz5sVUbeC_LyMZHRUz0',
    appId: '1:559471513334:ios:371796d88842bd60c6a6d7',
    messagingSenderId: '559471513334',
    projectId: 'sert-bec19',
    storageBucket: 'sert-bec19.appspot.com',
    iosBundleId: 'com.example.sert',
  );
}
